### ISSUE TITLE
Define libflux-security API

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-security#1]
A libflux-security.so API needs to be defined. This interface should at least include the following

 * key management: create keys, load keys, etc.
 * sign/verify attached/detached signatures of blobs and/or json documents

rfc15 talks about making the actual security implementation pluggable, so in this issue we would only include defining an API generic enough to work with multiple backend security and key management interfaces.

I'm not sure if the `flux_sec_*` interface from current `libflux/security.[ch]` should be moved here, or if that interface should be backed by libflux-security or what.

Also see @garlick's `zsigcert` class from the [imp-prototype](https://github.com/grondo/flux-core/blob/imp_prototype/src/common/libutil/zsigcert.h) experiment.

**Comment by grondo** [comment]
Talked with @dun and he suggests looking at libsodium as a starting point for abstractions that might work for libflux-security API.

I'm not sure yet what the proper interfaces might be, but perhaps it will be best to start simple with something like zsigcert (see above), though I think we found the json-signing variant a bit awkward, so perhaps think about a different representation for signed json.

We should also think about what other functionality libflux-security API might need to offer besides the two bullets above, though maybe that is ok to save for later.

**Comment by garlick** [comment]
Here are some docs on libsodium's detached and attached signature API FWIW

https://download.libsodium.org/doc/public-key_cryptography/public-key_signatures.html

**Comment by garlick** [comment]
libsodium has a [sodium_init()](https://download.libsodium.org/doc/usage/) function that initializes a "global context" of sorts for all of libsodium.

I'm thinking we might want something similar to parse a flux-security config file and maybe cache other state that can be reused, though I would lean towards an explicit context that has to be created and destroyed, and is passed to functions that need it.  Any thoughts on that @grondo?

**Comment by grondo** [comment]
Sounds good to me. We obviously need at least the `_init()` function to initialize libsodium it would seem... any idea how to handle that cleanly if `flux_security_init()` returns an explicit context?

I was kind of wondering if we'd have more specific interfaces in libflux-security so perhaps we'd have a `signer_t` `verifier_t` etc, and wouldn't need a global "security" context, but I'm not sure at this point if that is right or not...

**Comment by garlick** [comment]
I think we can close this general discussion and open issues on specific API functionality that we need.
