### ISSUE TITLE
imp: implement kill subcommand

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-security#103]
A `flux-imp kill` subcommand is compulsory with `flux-imp exec` or else a non-privileged instance will have no way to terminate jobs launched as a different user. `flux-imp kill` will verify that the requesting userid has permission to kill by checking if the target process(es) are in a cgroup owned by the user running the IMP. This should work since we have `Delegate=yes` set in our systemd unit file.

When we actually create cgroups for jobs, then the checks may have to be more subtle.

**Comment by garlick** [comment]
Closed by #110
