### ISSUE TITLE
imp: add PAM session management support to IMP exec subcommand

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-security#148]
In a Flux system instance, the Flux IMP is the piece of software which allows the unprivileged system instance owner (typically the `flux` user) to transition user credentials to the _guest_ users that are running jobs. Since the IMP is the only component of a system instance which is run with elevated privileges, any job or user setup which may require these privileges must take place in the IMP before it transitions userids and calls `exec(2)`.

One useful way to allow runtime configuration of IMP behavior would be to turn the IMP into a [Linux PAM](https://en.wikipedia.org/wiki/Linux_PAM) enabled application. This would entail calling into the [PAM API](https://www.man7.org/linux/man-pages/man3/pam.3.html) while the IMP is still running setuid root. I believe it would be sufficient to just execute the session management API calls, since the IMP has already authenticated the user via the signed J (therefore no authentication phase needed), and it is presumed that user's account is valid (no account management phase required). This would involve calling `pam_open_session(3)` and `pam_close_session(3)` along with necessary other PAM API setup and `pam_set_item(3)` calls etc.

Note; In order for the IMP to be able to call `pam_close_session(3)`, we'll need a solution for #147.

**Comment by garlick** [comment]
Resolved by #151 I think.  Open new issues if there's more to do.
