### ISSUE TITLE
need keygen utility for signing keys

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-security#16]
We need something similar to `flux keygen` for creating/updating signing keys.

Did we settle on how we wanted to add commands in this project?

If we want certs to be signed by the IMP, such a command would require access to the IMP's private signing key.

**Comment by grondo** [comment]
Yeah, seems like a CA type role would have to be an IMP subcommand, but you shouldn't need to run a setuid binary to create a pair of signing keys.

Should `flux-keygen` remain part of flux-core, but require code from libflux-security.so in order to create signing keys? This would allow even flux-core in a builddir to correctly use the system security library to create/manage keys. If we try to make `keygen` a `flux(1)` subcommand installed by flux-security project, things would seem to get messy real quick

**Comment by garlick** [comment]
Having `flux-keygen` reside in flux-core sounds good.

So if we had a `flux-imp ca` subcommand to provide a "CA signing service", would we provide API calls (such as new methods in sigcert) to interact with it, optionally?

**Comment by garlick** [comment]
Backing up, I was picturing that the sigcert class could have methods like
```c
int flux_sigcert_sign_cert (struct flux_sigcert_t *ca_cert,
                            struct flux_sigcert_t *cert);

int flux_sigcert_verify_cert (flux_sigcert_t *ca_cert,
                              struct flux_sigcert_t *cert);
```

These would sign `cert` with `ca_cert`, adding the signature to `cert` and verify `cert` with `ca_cert`, getting the signature from `cert`.  These would use internal methods to serialize `cert` for signing/verification purposes.

So the caller to `sign_cert` would need to provide the CA's private cert.  The caller to `verify_cert` would need to provide the CA's public cert, and also potentially check a list of revocations. 

It's feasible that `verify_cert` could be wrapped in another API call that parses an IMP config file and locates the CA's public cert and revocation list, which could be publicly readable.  This is probably a good way to go since it would need to be used wherever J needs to be validated if public certs are provided along with the signed J.

`sign_cert` needs access to the CA's private cert which cannot be publicly readable.  This could similarly be wrapped in an API call that parses config and locates the CA's private cert, but it could only be called from a process with read permission on the CA's private cert.

If `flux-keygen` lives in flux-core, it seems like it needs some way to call out to a service or executable in `flux-security` to do the CA signing.  Or maybe it should simply exec the IMP and outsource the whole job to this project?

Did you have any thoughts @grondo?

**Comment by grondo** [comment]
> The caller to verify_cert would need to provide the CA's public cert, and also potentially check a list of revocations.

Just my opinion, but it seems like the public calls should be at a higher level to avoid errors. For example, a naive caller might forget to check to the list of revocations so the API should make this impossible, if possible ;-)

Maybe something where you first have to initialize a verifier, which would load state from the system behind the scenes, then use that verifier in the verify calls?

> If flux-keygen lives in flux-core, it seems like it needs some way to call out to a service or executable in flux-security to do the CA signing. Or maybe it should simply exec the IMP and outsource the whole job to this project?

I was picturing a higher level `sigcert_sign_cert()` function that hid the details from the caller. If the site configuration says the IMP is acting as CA, then `sigcert_sign_cert()` could fork/exec the IMP to get the cert signature. However, if there is some other CA method, then a plugin to the security library would provide those methods.

This doesn't mean flux-keygen can't be in the flux-security project, though. I was trying to avoid it because any commands coming from flux-security project can't be handled in the same way as the flux-core commands (at least I couldn't think of a clean way to do it).

Sorry if I'm taking this issue on a tangent. I'll defer to you for any decisions here because I haven't thought about it too much. Maybe we should also ping @dun?

**Comment by garlick** [comment]
I agree with your points above @grondo.  Sorry my thoughts are a bit jumbled - still trying to get my head around the big picture.

One observation is that if a site chooses to use an existing infrastructure to authenticate jobspec, then key generation and management would likely be outside of Flux.  So I don't think it's feasible to have an abstract API that covers this in a mech independent way.

Maybe `flux-keygen [--signing]` (in flux-core) could exec an IMP subcommand like `/usr/libexec/flux-imp keygen`  for key generation.  `flux-imp keygen` could parse `/etc/flux-security.toml` (or similar) and if a mechanism other than the built-in CURVE one is selected, a site-configured error message could be displayed, such as:

> Policy at this site is to use Kerberos to authenticate Flux job requests.  Please follow instructions at _URL_  to obtain a Kerberos principal, and make sure you have run `kinit` before submitting Flux jobs.

It feels to me like `flux_signcert` represents one mechanism, and we need to separately discuss the abstract interfaces for signing/verification that work for any site-configured mechanism.  As such, maybe `libflux-security.so` should not export the `flux_signcert` class.

Another observation (for the flux_sigcert mechanism) is that the CA functionality could be limited by a site to a secure system, to avoid wide distribution of the CA private key.  So again the `/etc/flux-security/toml` could contain a site-specific error message if `flux-keygen` -> `/usr/libexec/flux-imp keygen` doesn't have access to the private key.

> Please login to flux-ca.llnl.gov to generate keys for signing Flux job requests.

**Comment by grondo** [comment]
> Another observation (for the flux_sigcert mechanism) is that the CA functionality could be limited by a site to a secure system, to avoid wide distribution of the CA private key. So again the /etc/flux-security/toml could contain a site-specific error message if flux-keygen -> /usr/libexec/flux-imp keygen doesn't have access to the private key.

Oh, hm, are you saying that `keygen --signing` would always try to certify the keys at the same time they are generated? I may have been confused in thinking that generating a keypair and then having them certified by a CA were two different steps. I think I see now why you wanted this to be an IMP subcommand, however, would it make things easier if they were kept as two steps? 

Then:

 * `flux keygen [--signing]` from flux-core presents the interface for creating keys and signing keys, with implementation provided by system installed libflux-security.
 *  If configured, `flux-imp ca` command can sign certificate requests for signing keys with the IMP's private key. Optionally the command may issue instructions for logging in to secure service or other method for getting keys signed (as you proposed above). If the site doesn't use CA certs as the method to distribute user's public keys, other instructions or redirect to site instructions could be provided. (e.g. users may have to register their public key with a PKI infrastructure like an IDM or by submitting their key to the blockchain :wink:)

I could be naive about how all this would *actually* work though...

**Comment by garlick** [comment]
So I think the plan is:

* `flux keygen` continues to live in flux-core and grows the ability to generate signing keys when we make flux-core dependent on flux-security.  flux-security will have to provide a public API for that.
* part of that process (implemented in flux-security) is to get the public cert signed by the CA, which may require the user to perform additional authentication or go to a secure system
* the public cert signing process ultimately should be an IMP subcommand hidden by public API above
* veriifcation of a public cert need not involve the IMP since it only needs the widely distributed and publicly available CA public key.  There should be a flux-security public API for this.

I'll go ahead and close this issue and open new ones for
* public API for signing cert generation and CA signing of public cert (#41)
* IMP ca subcommand for signing (to be used by public API above) (#42)
* public API for verifying public cert (using CA pub key and revocations) (#43)
