### ISSUE TITLE
imp: `kill` should not avoid signaling the job's IMP

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-security#184]
Problem: The `flux-imp kill` implementation takes pains to avoid signaling the IMP and instead delivers signals to the child of the IMP. The IMP forwards signals, so it is unclear why this approach was taken, perhaps just to handle the case of `SIGKILL`. In any event, this strategy should be rethought, especially if the IMP's signal handlers get more features like forwarding signals to all PIDs in the current cgroup or similar.

One strategy may be to only avoid signaling the IMP when the signal cannot be caught, like SIGKILL. 

Another strategy would be to remove `flux-imp kill` altogether, since it doesn't seem to be strictly required now that the IMP stays around as parent of the job shell.

**Comment by garlick** [comment]
> Perhaps we should add this to the RFC, then implement once we're happy with the results?

Good idea!

**Comment by grondo** [comment]
Given a recent update to RFC 15, the `kill` subcommand shall no longer be used for jobs started via `flux-imp exec`. Therefore we can close this issue in favor of one that specifies implementation of the updated RFC.
