### ISSUE TITLE
imp: implement signal forwarding specification from RFC 15

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-security#185]
The RFC 15 [signal handling](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_15.html#signal-handling) section now specifies:

> To enable the instance owner to fully clean up when the job shell is unable to do so, the IMP SHALL handle SIGUSR1 as a surrogate for SIGKILL. Upon receipt of this signal, the IMP SHOULD deliver SIGKILL to all processes in the job’s container, including the job shell.
>
> The IMP shall get the basename of the current cgroup directory at startup. If the directory begins with “imp-shell”, then the IMP SHALL deliver SIGKILL to all PIDs listed in cgroup.procs. Otherwise, the IMP SHALL deliver SIGKILL only to its direct child and optionally MAY include descendants.

This needs to be implemented.

**Comment by garlick** [comment]
Completed by #186
