### ISSUE TITLE
Create skeleton IMP

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-security#2]
A skeleton flux-imp should be created as an aid in bootstrapping other flux-security project infrastructure including testing, packaging. The IMP skeleton should be able to read an input on stdin, fail with obviously bad input, process options, etc.

Design decisions that need to be made for the skeleton IMP include: 
 * How do flux-imp subcommands work? (Do we pull in a copy of liboptparse, use liboptparse from system installed flux-core, or do something simpler here?)
 * How will flux-imp  be installed on the system. Should it be installed as a subcommand for the system `flux-core`, e.g. installed under `${libexec}/flux/cmd`, or should it be in `${bindir}` as `flux-imp`? (We're trying to avoid circular dependencies, but perhaps it is ok for flux-security to depend on installed system version of flux-core? See optparse question above) 
 * Where and how will we keep flux-imp configuration. What is the "skeleton configuration"? (authorized users, plugin configuration, plugin locations, default job shell, etc)

**Comment by garlick** [comment]
It seems like we've resolved most of these issues and we certainly have the skeleton IMP now.  Closing -
 reopen if you disagree @grondo.
