### ISSUE TITLE
configure: syntax error near unexpected token 'SODIUM'

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-security#39]
Suddenly getting this error on latest master
```
checking for ANSI C header files... (cached) yes
./configure: line 12586: syntax error near unexpected token `SODIUM,'
./configure: line 12586: `PKG_CHECK_MODULES(SODIUM, libsodium, , )'
```

Not sure if I'm  missing something in my current environment (c9.io), and `configure.ac` looks ok otherwise (and the PKG_CHECK_MODULES() hasn't changed), so I'm not sure what is going on.

Is this happening for anyone else?

**Comment by garlick** [comment]
Maybe a problem with missing pkgconfig package?

https://stackoverflow.com/questions/8578181/using-the-pkg-config-macro-pkg-check-modules-failing

**Comment by grondo** [comment]
Yeah, sorry, for some reason `aclocal` couldn't find pkg.m4. I gave up trying to find out why (may be because of side-installed version on c9 instance), and just copied into `config/pkg.m4`. Clearly my problem.
