### ISSUE TITLE
Define flux-security configuration file format

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-security#5]
The flux-security project will require one or more configuration files to allow site control of features. At the very least, the IMP may read system configuration to determine what users and/or groups are allowed to run a privileged version of the IMP in multi-user mode.

The configuration file format should be kept very simple to reduce the amount of code and potential for vulnerability during configuration parsing.

**Comment by grondo** [comment]
For flux-security purposes we probably only need key/value configuration file at first. Something like INI would work fine for this, and there are some very small ini libraries would could use out there:

  https://github.com/compuphase/minIni
  https://github.com/benhoyt/inih

Since we have to parse YAML anyway in the IMP at least, we could just use YAML for configuration files (like everyone else). This would allow more powerful configuration in the future, and is a nice, human-editable format.

Another interesting spec along these same lines is [TOML](https://github.com/toml-lang/toml), which is meant to be human readable/editable, but much simpler than YAML.

**Comment by garlick** [comment]
I've been using [this INI parser](https://github.com/benhoyt/inih) in a few of my personal projects.  Very simple.

**Comment by grondo** [comment]
Thanks, that seems to be the same as the second project referenced above.

If we want to standardize on config file format I'm not sure INI is sufficient. (doesn't support complex values). YAML might be more flexible on that front..

**Comment by garlick** [comment]
Maybe the same config file format could be used for certificates as outlined  (#7)

TOML looks pretty neat.

**Comment by garlick** [comment]
One interesting thing about TOML is that it converts neatly to JSON.  Presumably you could call something like `toml_to_jansson(FILE)` and just use the familiar jansson API to access your config stuff...

Come to think of it, a JSON library also gives you hashes and arrays, which might be an alternative to pulling in a list + hash implementation, like inevitably happens...

**Comment by garlick** [comment]
I think we've got all this mostly nailed down, so closing.
