### ISSUE TITLE
implement munge security mode

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-security#55]
We noted in discussions with @dun that munge could be used to sign J input.  Originally the munge TTL seemed incompatible with job requests that might sit in a queue for days or weeks, but actually, it is possible to ignore an expired TTL and still validate/extract payload from a munge credential.

Same goes for the replay restriction (it can be ignored at the discretion of the validator).

So it could be possible to implement a really simplified mechanism for signing J that uses munge only.  
It may not be a long term viable option since a system instance that spans multiple munge domains would be problematic.  But it might be fine for a single cluster Flux installation.

**Comment by garlick** [comment]
To summarize our discussion today:

The signer class will need to undergo some changes to accomodate multiple mechanisms, e.g
`signer_wrap()` should drop the `cert` argument, and `signer_unwrap()` should drop the `ca` argument.
Instead, a generic "setter" should be added  that allows the mechamism specific data to be set.  For example
```c
int signer_set (struct signer *signer, signer_opt_t option, ...);
```
with options for

* **SIGNER_OPT_MECHANISM**  select "munge", "flux-ca", and "none"
* **SIGNER_OPT_FLUX_CERT** set `const struct sigcert *` for flux-ca signing
* **SIGNER_OPT_FLUX_CA** set `const struct ca *` for flux-ca verification
* **SIGNER_OPT_MUNGE_CTX** set munge context for munge signing/verification

In addition, it will be necessary unwrap payload and header without validation as an option where validation has already been performed.

The representation of a signed payload is currently three base64 strings

HEADER.PAYLOAD.SIGNATURE

HEADER, which is a serialized then base64 encoded kv object, should include the security mechanism, and the userid in the generic portion.  SIGNATURE  should be the munge cred with its payload set to a hash digest of HEADER.PAYLOAD

**Comment by grondo** [comment]
Hm, I don't like how the `signer_opt_t` exposes the underlying mechanism. Ideally this scheme would be extensible to other security methods without modifying the `signer.h` header.

Could the mechanism be completely hidden behind a `struct signer` interface? If we consider how this would be used on a real system, the security mechanism and any tunable parameters would be set by system configuration anyway, so could the "munge" signer implementation take care of management of the `munge_ctx_t` so the caller of the `signer` class doesn't have to worry about it? (Same with CA and CERT?)

Perhaps this setup would be done in the `init` callbacks of all registered `signer` plugins, called during `signer_create` or a more specific `signer_init (struct signer *signer, cf_t conf)`?

**Comment by garlick** [comment]
That seems like a reasonable approach.  The only exception I can think of is maybe a tool for job submission would have an option to select a particular cert when the flux-ca method is used?

**Comment by garlick** [comment]
I was just toying with the following idea for a public API - a "secure message":
```c
typedef struct flux_secmsg flux_secmsg_t;

flux_secmsg_t *flux_secmsg_create (const char *config_path);
void flux_secmsg_destroy (flux_secmsg_t *msg);

int flux_secmsg_set_payload (flux_secmsg_t *msg, const void *buf, int bufsz);
int flux_secmsg_get_payload (flux_secmsg_t *msg, const void **buf, int *bufsz);

int flux_secmsg_sign (flux_secmsg_t *msg, int64_t ttl);
int flux_secmsg_verify (flux_secmsg_t *msg, int64_t *userid);

// possibly seperate HEADER accessors needed here for ctime, xtime, userid

const char *flux_secmsg_encode (flux_secmsg_t *msg);
flux_secmsg_t *flux_secmsg_decode (const char *input);
```

Does that seem like it might be on the right track?

**Comment by grondo** [comment]
At dentist office for kid right now, but I will take a look in a bit. 
Here's some initial thoughts off the top of my head: 

Will secure message config file really be read from disk for each message created?

Do you think the verify step would also need some configuration?  E.g. allowed security type for instance?

Would a "secure flux message" just end up as payload in a regular flux msg_t?

Would it work to have "creator" and "verifier" interfaces that are initialized from configuration, and this state is passed to creation and verification functions respectively, so that configuration could be read once?

Is there some existing project with best practices that we could borrow an interface from? (Apologies if you already did look at other projects)

Sorry if this isn't coherent, having trouble typing on my mobile

**Comment by garlick** [comment]
Hmm, thanks for those thoughts.  Reparsing the config file each time would be bad!  Yes I do think verification needs config (for accepted mech type, location of certs, etc)

Apart from libsodium which uses the wrap/unwrap interfaces similar to "struct signer", I haven't really surveyed.  That's what I'll do next, thanks.

**Comment by garlick** [comment]
A mini survey - just the primary sign/verify functions for libsodium, gnutls, and SSL.  There are other variants in each library, and at least for gnutls and ssl, accessorf functions, and dependencies on other library data structures that must be managed.

[libsodium](https://download.libsodium.org/doc/public-key_cryptography/public-key_signatures.html) combined mode, single part API:
```c
int crypto_sign(unsigned char *sm, unsigned long long *smlen_p,
                const unsigned char *m, unsigned long long mlen,
                const unsigned char *sk);

int crypto_sign_open(unsigned char *m, unsigned long long *mlen_p,
                     const unsigned char *sm, unsigned long long smlen,
                     const unsigned char *pk)
```
[gnutls](https://www.gnutls.org/manual/html_node/Cryptographic-Message-Syntax-_002f-PKCS_00237.html#Cryptographic-Message-Syntax-_002f-PKCS_00237) PKCS-7 signatures
```c
int gnutls_pkcs7_sign (gnutls_pkcs7_t pkcs7,
        gnutls_x509_crt_t signer,
        gnutls_privkey_t signer_key,
        const gnutls_datum_t * data,
        gnutls_pkcs7_attrs_t signed_attrs, 
        gnutls_pkcs7_attrs_t unsigned_attrs,
        gnutls_digest_algorithm_t dig,
        unsigned flags)

int gnutls_pkcs7_verify (gnutls_pkcs7_t pkcs7,
        gnutls_x509_trust_list_t tl,
        gnutls_typed_vdata_st * vdata,
        unsigned int vdata_size,
        unsigned idx,
        const gnutls_datum_t * data,
        unsigned flags)
```

[libssl](https://www.openssl.org/docs/man1.0.2/crypto/EVP_DigestSignInit.html)
```c
 int EVP_DigestSignInit(EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx,
                        const EVP_MD *type, ENGINE *e, EVP_PKEY *pkey);
 int EVP_DigestSignUpdate(EVP_MD_CTX *ctx, const void *d, size_t cnt);
 int EVP_DigestSignFinal(EVP_MD_CTX *ctx, unsigned char *sig, size_t *siglen);

 int EVP_DigestVerifyInit(EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx,
                        const EVP_MD *type, ENGINE *e, EVP_PKEY *pkey);
 int EVP_DigestVerifyUpdate(EVP_MD_CTX *ctx, const void *d, size_t cnt);
 int EVP_DigestVerifyFinal(EVP_MD_CTX *ctx, const unsigned char *sig, size_t siglen);
```

**Comment by garlick** [comment]
New idea discussed offline:  add a generic flux security context, e.g. `flux_security_t` that can capture the parsed config file, and use that as the persistent state between sign/verify calls ratehr than creating a new class to contain that.

This approach has worked out OK in the flux api, where the `flux_t` broker handle acts as a kind of catch-all API handle in some places.  For a start something like this?
```c 
typedef char flux_error_t[200];

typedef struct flux_security flux_security_t;

flux_security_t *flux_security_create (void);
void flux_security_destroy (flux_security_t *ctx);

int flux_security_configure (flux_security_t *ctx,
		             const char *pattern, flux_error_t error);
```
If `pattern` is NULL `flux_security_configure()` can use a compiled-in install path for the config glob?

**Comment by grondo** [comment]
I don't have a problem with the above, but it would be nice if `flux_security_create` and `flux_security_configure` could be combined as is done for `flux_t`, e.g. 

```C
flux_security_t *flux_security_open (const char *pattern, int flags);
```
(Maybe open is the wrong verb and `create()` would be more correct, also maybe flags not needed)

Might also want to wrap the `flux_error_t` character array in a struct in case more information were needed in the future (less callers would need to be updated), but perhaps an "error accessor" function to return the last error might also be more future-proof? e.g.

```C
int flux_security_last_errnum (flux_security_t *sec);
const char * flux_security_last_error (flux_security_t *sec);
```

Just throwing more ideas out there for now.. not strongly arguing for this approach.

**Comment by garlick** [comment]
Cool, those both sound like improvements.  Will go wtih those.

**Comment by garlick** [comment]
Oh, except with the two ideas together then you can't capture a config file parse error, since in that case you wouldn't get back a valid `flux_security_t` to interrogate.

**Comment by grondo** [comment]
ugh good point!

**Comment by garlick** [comment]
I'll submit a PR that implements the basic context and maybe we can transfer the discussion over to that since I feel like we sort of have a good start on a design.

**Comment by grondo** [comment]
Ok, Thanks! Yeah, this issue was supposed to be about the MUNGE case huh?

**Comment by garlick** [comment]
Back to the generic signing API - would does something like this make sense?  The "smsg" would encapsulate payload and metadata.  Unlike the previous proposal, configuration including mechanism selection, certificates, etc. can be cached for signing and verification in the `flux_security_t` context.  The context also simplifies error handling a bit.
```c
typedef struct flux_smsg flux_smsg_t;

flux_smsg_t *flux_smsg_create (void);
void flux_smsg_destroy (flux_smsg_t *smsg);

flux_smsg_t *flux_smsg_decode (const char *input);
const char *flux_smsg_encode (flux_smsg_t *smsg);

int flux_smsg_set_payload (flux_smsg_t *smsg, const void *buf, int bufsz);
int flux_smsg_get_payload (flux_smsg_t *smsg, const void **buf, int *bufsz);

void flux_smsg_set_userid (flux_smsg_t *smsg, int64_t userid);
int flux_smsg_get_userid (flux_smsg_t *smsg, int64_t *userid);

int flux_smsg_set_ttl (flux_smsg_t *smsg, int64_t ttl_seconds);
int flux_smsg_get_ctime (flux_smsg_t *smsg, time_t *ctime);
int flux_smsg_get_xtime (flux_smsg_t *smsg, time_t *xtime);

int flux_smsg_sign (flux_smsg_t *smsg, flux_security_t *ctx);
int flux_smsg_verify (flux_smsg_t *smsg, flux_security_t *ctx);
```

**Comment by grondo** [comment]
I'm not sure I have any comments at this time. Haven't thought enough about the use case to know what is best here.

However, I found it surprising that the caller can set a ttl or userid(!) on an smsg, I would have thought that would come from configuration in the `flux_security_t` configuration. Also, for any mechanism I can think of, setting the userid should be a side effect of the signature? (Does it even make sense to set the userid outside of `sign` operation with MUNGE for example?)

My only other thought is if it would make sense to combine `sign` and `encode`, since I'm not sure what you'd want to do with an `smsg` between `sign` and `encode`.

If we think we'll want to be able to add more generic/extensible metatdata to a smsg, we may want to expose a subset of the `struct kv` interface as `flux_smsg_get ()` `flux_smsg_set ()` but that might be getting to ahead of ourselves (I'm thinking this would allow the jobspec to be set as payload and other signed members of **J** to be signed metadata in an *smsg* construct. That might be convenient but I'm totally not sure if it is the right approach. Maybe we'll want to diagram out this one use case at least...)

Sorry I'm not more helpful.

**Comment by garlick** [comment]
I guess I should reference #59 here, where I propose NOT introducing a container for "secure messages" after all.  Sorry for all the off topic noise I made in this issue while brainstorming.

Back to the topic of the issue, any thoughts on how to test a munge based mechanism in travis?   I'm sure we can check if munge is running and have sharness conditionally skip if not, but could we either configure and start munge as part of the initial travis setup, or start/stop from within sharness?

**Comment by grondo** [comment]
We should plunder @dun's sharness setup for MUNGE testing in travis. I think he has some magic to start the daemon at the beginning of each sharness unit.

**Comment by dun** [comment]
For sharness, take a look at [munge/t/0010-basic.t](/dun/munge/tree/master/t/0010-basic.t). `munged_start_daemon` is called at the start of the tests, and `munged_stop_daemon` is called at the end. Those functions are defined in [munge/t/sharness.d/03-munged.sh](/dun/munge/tree/master/t/sharness.d/03-munged.sh). Or just browse the [tests](/dun/munge/tree/master/t).

`munged_stop_daemon` on master uses the new `munged --stop` command-line option, so you'll want to use an older [03-munged.sh](/dun/munge/blob/e412443f581c38a0cea7a9533684c2eba033a2e3/t/sharness.d/03-munged.sh) if you're running an older version of munged.
