### ISSUE TITLE
define IMP input format

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-security#6]
RFC 15 defines the input to the IMP, and requires that it be supplied to the IMP on stdin.  We need to define a simple format for this input, and some security API calls for manipulating it.

The RFC calls out the following specific items:
* Local assigned resource set (Rlocal)
* Options supplied by resource owner
* User Request (J) (described below)

Where J is the User Request or reference to such a request, which SHALL contain
* Jobspec as per 14/Canonical Job Specification
* Options supplied by guest user
* Guest user uid or username
* Job shell path
* UUID
* Timestamp and TTL
* Intended recipient (instance owner)
* Allowed resource set
* User signature (of above fields)

**Comment by garlick** [comment]
We could have the input be a single JSON object (IMP reads to EOF and parses the whole thing).  The YAML jobspec could simply be encoded with base64 and represented as a JSON string.

For signing JSON object (like J) we might want to look at:

[RFC 7520: Examples of Protecting Content Using JSON Object Signing and Encryption (JOSE)](https://tools.ietf.org/html/rfc7520)

A blog post on the subject

https://ordina-jworks.github.io/security/2016/03/12/Digitally-signing-your-JSON-documents.html

**Comment by garlick** [comment]
The RFC for JOSE's signing protocol:

[RFC 7515: JSON Web Signature (JWS)](https://tools.ietf.org/html/rfc7515)

Criticism of JOSE/JWS:

https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid

Overview of some other options for signing JSON objects:

https://dzone.com/articles/json-message-signing-alternatives

**Comment by grondo** [comment]
I had looked at this before and [CBOR](cbor.io) looked interesting (found in your final reference above). I did find a C implementation for CBOR [here](http://libcbor.org/).

**Comment by garlick** [comment]
Just reviewing what we did in the earlier prototype for JSON signing.  The prototype is described here:

https://github.com/flux-framework/flux-core/wiki/flux-mock-imp-experimental-prototype

We used libsodium to generate signing keys, which were stored in $HOME/.flux.  The process was wired into  `flux keygen`.  The keys used a "certificate" format derived from czmq's [zcert](http://czmq.zeromq.org/manual:zcert).  In fact, `zcert` was just copied and modified into a new class called `zsigcert` which handled the certificates as well as JSON signing and verification.

The JSON signing scheme was patterned after the one chosen by camlistore:

https://camlistore.org/doc/json-signing/

**Comment by garlick** [comment]
Just thinking through what we don't like about the camlistore method.

One problem is that you risk invalidating the signature if you try to embed a signed JSON object in another object (for example in a request or response message payload).  This is because the signed object is output in encoded (string) form.  If you decode  it, wrap an object around it, and encode the enclosing object, your JSON library may encode the signed portion differently than

**Comment by garlick** [comment]
It seems like one of the objectives the camlistore method is not needed in our case.  We don't need the signer and the verifier to be able to use different JSON libraries because we're going to implement one library that both signs and verifies (libflux-security.so).

If we lift the signature up a level from the protected contents (compared to camlistore), then everything is fine, e.g. say we want to sign this object:
```json
{"foo":42,"bar":53}
```
we can encode it and pass it to something like
```c
int flux_sec_sign_json (cert_t *cert, const char *json_in, char **json_out);
```
which would decode `json_in`, canonically encode it, calculate signature over canonical encoding, then enclose decoded object in security envelope, and encode _that_, returning maybe something like
```json
{
 "protected":{"foo":42,"bar":53},
 "signature":{"ed25519-ffncnpulos87Bs21RtxiXmZE9J66cFKeSo="}
}
```
The user can decode the security envelope, embed it in another object, encode that, ship over the network, decode, extract security envelope, re-encode, and pass it to something like
```c
int flux_sec_verify_json (cert_t *cert, const char *json_in);
```
which would decode  `json_in`, extract "protected" object, canonically encode it, validate signature.

**Comment by grondo** [comment]
That seems reasonable, but when I looked at this before there were a lot of strange corner cases that made perfect canonicalization difficult. Since the canonicalization occurs only under libflux-security.so, we'd only have to promise that we never ever ever change it. ;-)

Canonicalization might also be useful outside of libflux-security.so, though. For example canonicalizing an object before putting into the content store could be useful to avoid storing the same data multiple times...

**Comment by garlick** [comment]
I could well imagine that there might be some corner cases in trying to canonicalize, particularly after a foreign JSON implementation has decoded and re-encoded, possibly altering JSON number precision or character encoding of JSON strings.  Hmm.

Well I guess the safer alternative is shipping
```json
{
 "protected":"eyJmb28iOjQyLCJiYXIiOjUzfQo=",
 "signature":{"ed25519-ffncnpulos87Bs21RtxiXmZE9J66cFKeSo="}
}
```
like JOSE, and then you have an extra decoding step when you want to look at the original object.  Not necessarily that big of a deal.

**Comment by garlick** [comment]
Probably this can be closed.  We still need to define the input to the IMP exec subcommand, but we've resolved the main issues discussed above with kv.h and signer.h, at least for now.

**Comment by grondo** [comment]
Thanks, I'll open up a separate issue for the IMP exec command, for which the input is one task thereof
