### ISSUE TITLE
How to select different signer mechanism for flux_sign_wrap?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-security#62]
Flux utilities making use of `flux_sign_wrap` will need to read default system `[sign]` config table in order to properly create signed data in a form accepted by the system installed IMP. This is straightforward when interacting with a system instance, since all system-wide config should apply.

However, if a child instance wants to allow tools/utilities to use an alternate signer mechanism for `flux_sign_wrap` there is currently no way to do this since only one `sign.default-type` is stored in configuration. For instance, a single user instance may be able to use the "none" signature mechanism instead of the more secure mechanism of the system instance `sign.default-type`.

Users of `flux_security_t` and `flux_sign_wrap` should somehow be able to select an alternate `sign.default-type`, either via exposing the `flux_security_t` config values in some way, or as another parameter to `flux_sign_wrap`. Callers of this interface should get a warning if the selected mechanism isn't supported by system configuration.

Another question would be where and how a tool like `flux run` would decide that it could fall back to "none" signer mechanism. Perhaps a requirement for some sort of "discovery" for these tools should be written into global flux requirements/plans.

Of course, this isn't a critical issue now since it doesn't hurt to use the more secure system-configured `sign.default-type`, but thinking about how the interface would look might be illustrative.

**Comment by garlick** [comment]
Adding a `const char *mechanism` argument to `flux_sign_wrap()` seems entirely reasonable.  Then a command could override the default mechansim if it wants.

I'm starting to wonder if maybe "unwrap" should do its best for any of the known mechanisms, provide a way to tell which mechanism was used, and then let the caller apply "allowed-types" after the fact, since in addition to site policy, the context is important too (who is calling unwrap and do we have other knowledge such as a peercred that makes e.g. mechanism=none acceptable).

**Comment by grondo** [comment]
That seems perfectly reasonable to me. An IMP being run where ruid == target uid could also accept mechanism==none.

**Comment by grondo** [comment]
> I'm starting to wonder if maybe "unwrap" should do its best for any of the known mechanisms, provide a way to tell which mechanism was used, and then let the caller apply "allowed-types" after the fact, since in addition to site policy, the context is important too (who is calling unwrap and do we have other knowledge such as a peercred that makes e.g. mechanism=none acceptable).
￼
On the other hand, flux-security APIs should probably be designed to "fail securely" and it might be too easy for the casual programmer to "forget" to apply the allowed-types after the fact and create a security hole.

This could easily be resolved however, by offering users a `flux_sign_unwrap_nocheck()` or similar that returns success if the payload can be "unwrapped", and a separate helper function to ensure the signing mechanism is actually allowed. However, the default `flux_sign_unwrap()` would perform both steps, and fail if the wrapped blob is invalid for any reason, including invalid signature or invalid signature mechanism.

**Comment by garlick** [comment]
Yeah that sounds right!
